server:
  port: 7979
  servlet:
    context-path: /cloud

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

cors:
  allowedOrigin: ${ALLOWED_ORIGIN}

jwt:
  secretKey: "wGhTdSC5wNkr7/Y6WAJGRd4tGyTILYA4ceU2hTLldwRqbwbkX3zeuB0Ra692dawd"